### ISSUE TITLE
Help to orient future development

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#100]
Two years and 99 issues since this project started, I would like to get some feedback on how to orient, organize and optimise future development. Some background on the project status and mission is in [ABOUT.md](https://github.com/loleg/dribdat/blob/master/ABOUT.md). Additional discussion is on a related [forum thread](https://forum.schoolofdata.ch/t/help-wanted-hack-the-hackathon-platform/247/1). Or you can jump straight into the [project board](https://github.com/loleg/dribdat/projects/1) to help sort through top issues.

---  

At time of writing there are 217 hackathon projects in the [make.opendata.ch wiki](http://make.opendata.ch/wiki/project:home), 90 projects published on [hack.opendata.ch](http://hack.opendata.ch), 21 at [now.makezurich.ch](http://now.makezurich.ch) and dozens more on archived sites like [IoT 2015](https://datalets.ch/dribdat/iot-2015/event/1/) and [1001001](http://bd.schoolofdata.ch/event/1.html). Many, many more are published by the open data community on other platforms (GitHub, OGD portals, university websites, etc.)

On their own, each of these is an interesting and inventive contribution to the community, the beginnings of a grassroots collaboration, a research direction, a startup... As a whole, the projects can be a rich source of information both on the history/evolution of the open data movement, as well as a references to the experience of participants with various data sources and platforms. Our old wiki platform has many downsides - first and foremost the difficulty to aggregate data about projects (status, team members, etc.) - which was one of the motivators for [Dribdat](http://github.com/loleg/dribdat), something that has been worked on with contributions and support from several core members the Opendata.ch community.

We have been discussing the idea of running more development sprints on Dribdat: updating it's backend, giving the frontend a refresh, further work on the [chatbot interface](https://github.com/loleg/sodabot) and adding a better mobile frontend, moving it within the main infrastructure at [Opendata.ch](http://opendata.ch) (it is currently hosted on the server of [Datalets.ch](http://datalets.ch)), migrating data from past events on [Make.Opendata.ch](http://make.opendata.ch), integrating it with our community platforms (sites, blogs, forums, social media), and scaling it out to many more events and users using a SaaS model (click a button to start your own hackathon..)

Critically, this all should be done with a view to the wider usefulness of the tool, so it would be great to solicit feedback and collaboration from Open Knowledge and other closely aligned communities.

The sprint goal could sound something like this: *develop our framework for bootstrapping and supporting projects from hackathon to startup, with a focus on community building, event support, use of data sources, and documenting progress, with plug-in support for on-prem and on-cloud collaboration*. A longer term organisational goal could be: *create the go-to platform for discovering, certifying and funding development of open data sources*. As a stretch goal, we could: *promote the cause of open development and open data, hackathons and civic activism, invite contribution and use by the international community*.

The project has so far progressed mostly on contributions of free time, about 2 K CHF allocated towards short sprints out of the budget of events over the past two years. Even a small amount of motivation or support from the user community would help to motivate progress. 

Here are some ways I can think of that people could contribute:

- check out past hackathons, e.g. http://hack.opendata.ch
- join a Dribdat-powered hackathon, e.g. http://make.opendata.ch 
- install and use the software yourself, see http://github.com/loleg/dribdat
- review the architecture, comparing this to similar platforms
- review [open issues](http://github.com/loleg/dribdat/issues), propose other improvements
- contribute to the Python code base

With moderate support, we could move to better infrastructure and support a self-service model, and carefully migrate project data to showcase a variety of community initiated open data projects. With good funding, all of the above plus integration with data portals and community tools could be imagined. With significant resources, and greater purpose, we could potentially rewrite the whole project using modern technologies like streaming data, reactive programming, blockchains, etc. But we need to start somewhere: spend at least a little time this summer dusting off the code base and closing some of the issues, and all kinds of contributions and support are welcome.

If you are interested in helping us to move forward with these plans, or think we should stop right here and do something more productive: please leave a note or just click the voting button as a sign of support. Thanks! -- @loleg

**Comment by tamberg** [comment]
Thanks for the great work! Happy to recommend Dribdat anytime. How about focusing on sustaining the current feature set and ensuring that past results remain accessible (as you already do)? Maybe that sounds a bit unambitious but sometimes simple and reliable tools are quite useful, e.g. cURL.

**Comment by loleg** [comment]
Thank you @tamberg for that really excellent point. I would also quite like to go the way of [Frictionless Data](https://frictionlessdata.io/), focusing on collecting data and making tools around it. I'll take your suggestion as a vote in favor of focusing on the data model, aggregation and API, allowing for development of various apps / frontends in a later sprint.

**Comment by loleg** [comment]
I've set up a [project board](https://github.com/dataletsch/dribdat/projects/1) where we can sort through the top improvement requests and bugs, as well as consider more fundamental concerns. It's not perfect but it's a start! At least, potentially a better start than just from the top of the list :-)

![dribdat-issues](https://user-images.githubusercontent.com/31819/72538202-bf504e00-387d-11ea-9cc7-d6cc98621b76.png)

**Comment by loleg** [comment]
Things have come a ways since issue #100 - dribdat is about making hackathons more visible, simple to understand/ run/ participate in, and an easy way to generate tangible (feedback, creative content) and intangible (goodwill, buzz) return for investment. There's a bit more detail on the current outlook at https://hackmd.io/@oleg/r1LUA87gU

**Comment by loleg** [comment]
The [new website](https://dribdat.cc) ([source here](https://github.com/dribdat/www.dribdat.cc)) tackles this problem head on. It would be great to get some feedback, but I am going to close this old issue and instead propose that you reach out via a new issue, leave us a note on [Twitter](https://twitter.com/dribdat), or use the contact form on the site if you have ideas for the roadmap.
