### ISSUE TITLE
Ideation via public repo issues

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#102]
From @cotting a request for an ideation board feature:

> How could we facilitate the idea creation before the event? Like letting anyone make challenge proposals and let the rest of the community comment those ideas.

[Open Data Day Zurich](https://hack.opendata.ch/event/7) had some JavaScript in place to connect to the GitHub API, and collect the list of challenges - posted in the form of [issues](https://github.com/OpenDataDayZurich2016/ideas/issues) in a dedicated repo. It might certainly help some organisers to have this out of the box, with perhaps some alternative engines supported (Sparkboard? Trello?...)

**Comment by loleg** [comment]
@gonzalocasas you have recently requested this again, and I think it's time to standardize the code into the platform. We can start with GitHub issues, but make it possible for other repo hosting sites' issues to be fed into a feed at the top of the Resources section. That way, we would be encouraging not just participants to use open source communities to host their projects, but also the organizers. Maybe even the README should be synced into the event description or something, but we can start with this for now.

**Comment by gonzalocasas** [comment]
👍

**Comment by gonzalocasas** [comment]
How would they be integrated? Would they be automatically imported as "Projects" within a predefined category? (In MakeZurich's case, we have an "Open challenge" category, and these should go there).

**Comment by loleg** [comment]
We used GitHub's new Discussions for an ideation board at [a recent event](https://github.com/cividi/geohackmin/discussions). They were at the time still in private Alpha for API access, so we had no way of integrating them with Dribdat. The tool was popular, but it had also a lot of limitations in the user interface. Ultimately, I'd like dribdat to be able to connect to a variety of ideation platforms. Is there no "Commenting spec" analog to OAuth? :thinking:

**Comment by loleg** [comment]
For now, I have resolved this by making the GitHub Issues widget we have used in the past included out of the box.
