### ISSUE TITLE
Integration with community platforms

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#115]
We already have integrated our platform with several Single Sign-On providers and chatbots. However, we want to be able to support other and potentially multiple community platforms. What do we mean by this? These are the platforms where interaction and exchange takes place between participants. These could be GitHub discussions, Slack channels, Gather spaces. The goal of this ticket is to clarify what "integration" means.

The questions are:

- Which integrations make the most sense to our users?
- Do mechanisms are there to provide integration?
- What barriers are there to implementation?

Additionally it is important to put more weight behind integration with other open source platforms. Adding [Mattermost support](https://github.com/loafoe/hubot-matteruser) to [dridbot](https://github.com/hackathons-ftw/dridbot), SSO and full aggregation support for [GitLab](https://docs.mattermost.com/deployment/sso-gitlab.html), easier integration with [Discourse](https://meta.discourse.org/t/discourseconnect-official-single-sign-on-for-discourse-sso/13045).

The task here is to research the options, suggest which route would be most straight forward, and implement the integration. See also https://github.com/dataletsch/dribdat/issues/118

**Comment by gonzalocasas** [comment]
One interesting avenue for generic integration would be to add `Incoming webhook` as an integration method. This would enable any platform with the ability to send http request to integrate into dribdat. For example, an IoT app (eg. using TTN) could feed sensor data into the project's activity directly.

Regarding the specific mechanism for integration, I guess each project would get a webhook automatically assigned. The question remains partly open as to which format the webhook payload would take. One would be a comment-like input (the minimum would be `{'text':'blablabla'}`), but there's surely room for extension, maybe following slack's format, with something like `{'text':'blablabla', 'data': {'temp': 23.34, 'humidity': 0.52}}`

**Comment by loleg** [comment]
Your comment is a fascinating idea. Webhooks are a simple and open standards based way of connecting the dots. I like the [Photon ThingSpeak](https://www.hackster.io/sentient-things/thingspeak-particle-photon-using-webhooks-dbd96c) example after looking around the web. [Datacake](https://docs.datacake.de/lorawan/get-started) seems to have a tip top process around this too. 

It reminds me of one of our first issues, #3 - an attempt to connect to an IoT app at the beginning of the project. I've been thinking about a similar approach with GitHub's API in #2 and  Having tags or PR merges or releases reflected make more sense to me with Git, rather than having every single commit reflected in the project log. In the same way, I could see an aggregate, a sample from the last 10 minutes of sensor readings or so, to be a useful indicator of progress. How about we start with just a blip on the timeline - "sensor is online"? Then we could move up next to just a reading of "X data points per minute across Y nodes". 

A badge might also be a lower hanging fruit - see #129

**Comment by gonzalocasas** [comment]
I like the blip idea ;)
![image](https://user-images.githubusercontent.com/933277/95821769-e06d9e80-0d2a-11eb-8c32-7fd30e1c8145.png)

**Comment by loleg** [comment]
@gonzalocasas let's dust off the "IoT blips" discussion in a dedicated issue #315

I'll start also specific issues for forum / ratings integration.
