### ISSUE TITLE
Sync replacing "Banner image link" with user's profile

### ISSUE THREAD

**Issue by philshem** [dribdat/dribdat#121]
When I sync from the linked Github repo's Readme.md, the project page replaces any existing Banner Image with the user's profile photo from Github.

I think this is not desired behavior, because the user's github profile photo has nothing to do with the project. Possible solutions would be a "banner.png" file in the Github repo, or just removing the sync for "Banner image link" if it has been manually set.

**Comment by loleg** [comment]
Thanks for raising this @philshem - but it felt like adding the GitHub profile would be better than nothing at all. And many projects start their own organisations, which have an appropriate logo.

However, the second point you mention - not overriding fields on sync - is a very much desired improvement, and is already being tracked in #83

**Comment by loleg** [comment]
Tested, all OK, closing.
