### ISSUE TITLE
Explain project architecture

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#133]
To help new developers understand the platform, it would help to have a basic diagram outlining the software architecture. In fact, at this point we should be thinking about whether the current project even is worthy of the term, or to propose a new architecture (microservices, anyone?) for the next-generation platform.

Here is something I relatively quickly put together to "get the ball rolling":

![architecture-dribdat svg](https://user-images.githubusercontent.com/31819/53130717-51b37900-356b-11e9-8c82-075cd9355eb2.png)

Note that this project is derived from https://github.com/sloria/cookiecutter-flask - on whose pages you can find some guidelines about the main structural features.

**Comment by loleg** [comment]
@gonzalocasas thanks for the thumb. Anything else I should add, do you have any comments, or can I just incorporate as-is into the README?

**Comment by gonzalocasas** [comment]
LGTM! 👍
