### ISSUE TITLE
Error rendering naive datetime in utils.py

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#135]
```
File "/srv/dribdat/dinacon/dribdat/templates/public/event.html", line 136, in block "content"
    <a href="{{ url_for('public.home') }}" class="btn btn-sm btn-primary">{{ current_event.countdown|until_date }}</a>
File "/srv/dribdat/dinacon/dribdat/app.py", line 99, in until_date
    return timesince(value, default="now!", until=True)
  File "/srv/dribdat/dinacon/dribdat/utils.py", line 25, in timesince
    now = datetime.now().astimezone(timezone)
ValueError: astimezone() cannot be applied to a naive datetime
```

@jibaku is this something you could take a quick look at? It looks related to #70

**Comment by jibaku** [comment]
@loleg is it occuring in some views or in the API ? Do you have a more precise traceback ?

**Comment by loleg** [comment]
@jibaku only on the event view, and only if it is a current event. I've added a couple of lines to the traceback so we can see the template excerpt.

**Comment by loleg** [comment]
Also, I noticed that `dribdat/settings.py` doesn't pick up the TIME_ZONE from the environment.

**Comment by jibaku** [comment]
> Also, I noticed that `dribdat/settings.py` doesn't pick up the TIME_ZONE from the environment.

For this it's done on purpose. We may want to host multiple instance of dribdat with different time zone for a same website. So I choose to keep it in the settings.

But using maybe a DRIBDAT_TIME_ZONE env var could be a improvement for later.
