### ISSUE TITLE
Event registration system

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#152]
How to register participants for a hackathon is a very common question with a rather stubborn answer.

Currently there is a simple way to use Dribdat to keep track of who has registered for an event: simply log in for a user account JOIN any challenge that has been posted to the event site. There is a Participants link at the bottom of the Events page which takes you to a [page like this](https://db.schoolofdata.ch/event/4/participants) for an overview of who's coming. This has not been widely tested, could use some design improvements, and the main problem with this is the still quite lousy auth in place and until #150 is resolved I wouldn't suggest this to everybody.

A simple TypeForm or Google Form works well for many events, though it is nice for people to have something like Doodle.ch, Tipo.ch or Eventbrite to be able to cancel their tickets. There are open source ticketing platforms that we could look into connecting to the project.

Any recommendations?

**Comment by gonzalocasas** [comment]
> Any recommendations?

Eventbrite integration would be awesome

**Comment by loleg** [comment]
Eventbrite has an [API](https://www.eventbrite.com/platform/api) which supports OAuth 2, and I can see this should be reasonably straight forward to use it to enable log-in to Dribdat. Do you mean anything else by "integration", @gonzalocasas ?

**Comment by loleg** [comment]
The typical use case here seems to be to compare the lists of registrants. I'm not sure there is enough friction here to warrant much more effort than a more prominent "Register now!" button, which I've just added.
