### ISSUE TITLE
Make external content more prominent

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#175]
When a team decides to mostly document in a README, the sync'ed content should be more prominent than the local content. Perhaps we could decide based on the content-length and position accordingly. 

Additionally, the feature of [dribdat2](https://github.com/hackathons-ftw/dribdat2_frontend) which visualizes contribution histories and other data from the remote location would be great to explore, even just in the form of a small banner making it clear where the content is coming from.

While we're at it, how hard would it to be to support multiple externals, i.e. a slideshow, data science notebook, scrapbook ...

**Comment by loleg** [comment]
I'm working on a [branch](https://github.com/loleg/dribdat/tree/175-externals), experimenting with a tabs layout:

![Screenshot from 2020-10-10 22-25-12](https://user-images.githubusercontent.com/31819/95664377-94163900-0b47-11eb-923d-b3ca9e3bf859.png)

**Comment by gonzalocasas** [comment]
Looks very good! Very clear 💯
