### ISSUE TITLE
Built-in PDF preview

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#196]
Since a lot of pitches are basically just PDF's, it would be nice if dribdat handled in-browser rendering for the preview, similar to how [GitHub's PDF Viewing](https://github.blog/2015-03-17-pdf-viewing/) works. Some popular workarounds currently include [nbviewer](https://github.com/jupyter/nbviewer) for GitHub-hosted PDFs, [Google Docs viewer](https://docs.google.com/viewer?url=${link_to_raw_pdf}) and https://speakerdeck.com/ - but no method is intuitive enough for general usage.

Currently we recommend this in the Getting Started instructions, but as it is such a common need it would be good to have at least some guidance directly on the project edit page.

For inspiration see [Wikipedia app](https://gitlab.com/Wikipedia-in-Schools/cordova-app/commit/ef451cd3b484815e1802db7139e917705cbca00e) and [pdf-viewer](https://gitlab.com/JBeen/pdf-viewer).

**Comment by loleg** [comment]
Mozilla's [PDF.js](https://github.com/mozilla/pdf.js#online-demo), as used by [CKAN's pdfview](https://github.com/ckan/ckanext-pdfview) seems like a good option.

**Comment by loleg** [comment]
See also [PDFObject](https://pdfobject.com/examples/pdfjs.html) with PDF.js fallback. Note due to CORS issues we should proxy resources through the app.

**Comment by loleg** [comment]
One of the big barriers to this solution is the file size limitation. Could we automatically optimize PDFs after upload? On Linux, I use `ps2pdf -dPDFSETTINGS=/ebook` to squish down files. This is a [Ghostscript](https://pypi.org/project/ghostscript/) tool with [Python bindings](https://ghostscript.readthedocs.io/en/latest/LanguageBindingsPython.html) available.

**Comment by Halil-Kuray** [comment]
The project I am developing as one of my internship duties: https://github.com/Halil-Kuray/Certification-Issue
