### ISSUE TITLE
Running tests with a Github Action

### ISSUE THREAD

**Issue by jibaku** [dribdat/dribdat#220]
Should the test suite be run using Github Action, since TravisCI is not giving a lot of free credits to open source anymore.

See also https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by loleg** [comment]
Thanks for the tip @jibaku, will consider it. Am quite used to TravisCI and have not yet had a chance to explore GitHub Actions. I could think of some interesting ways we could use it in the context of this project. You're very welcome to add the requisite configuration and get the ball rolling!

**Comment by gonzalocasas** [comment]
https://github.com/hackathons-ftw/dribdat/pull/221

**Comment by jibaku** [comment]
@loleg at the end @gonzalocasas was much faster than me to add it.

**Comment by loleg** [comment]
Just one point of clarification, Travis CI is still providing 10'000 free
credits and the option to get unlimited credits for accredited Open Source
projects.

*"Free for open source. We love the Open Source Community, and to show how
much we love it, upon validated request placed with our Support Team you
may receive free OSS credits for your public builds." *
https://travis-ci.com/plans

>

**Comment by gonzalocasas** [comment]
The most compelling argument for GH is build speed rather than free minutes.

**Comment by loleg** [comment]
Cool. Let's add a badge before we close this issue.
https://medium.com/swlh/automate-python-testing-with-github-actions-7926b5d8a865

**Comment by gonzalocasas** [comment]
Fixed on https://github.com/hackathons-ftw/dribdat/pull/221
