### ISSUE TITLE
Fix escape sequence in apifetch

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#223]
Warning in test run:

```
dribdat/apifetch.py:60
  /home/runner/work/dribdat/dribdat/dribdat/apifetch.py:60: DeprecationWarning: invalid escape sequence \g
    "![\g<1>](https://raw.githubusercontent.com/" + json['full_name'] + '/master/',
```

Python is refreshing the [string literal syntax](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals).

**Comment by tirkarthi** [comment]
I have created https://github.com/hackathons-ftw/dribdat/pull/230 to fix this.
