### ISSUE TITLE
GitHub login support

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#227]
It's about time that we make it possible to login through GitHub. This is easy to add, though support for multiple SSO providers would need some refactoring. Not clear to me yet is also if we can define one global app to make it easier to set up.

This has been started with an initial PR in #228, however, it needs additional testing in particular to address the issue of token expiry described in [flask-dance#35](https://github.com/singingwolfboy/flask-dance/issues/35#issuecomment-160617138) thrown by `dribdat/public/auth.py`, line 235, in github_login.

See [official docs](https://docs.github.com/en/developers/apps/identifying-and-authorizing-users-for-github-apps) and #115

**Comment by loleg** [comment]
This has been working reasonably well so far, however I sometimes get an error "Access denied to GitHub" which goes away on a second attempt to log in. Anyone else seeing this?

**Comment by gonzalocasas** [comment]
@loleg is there an instance I could test this on? (besides setting it up locally, of course)

**Comment by loleg** [comment]
@gonzalocasas yes, running at https://cividi.space

**Comment by gonzalocasas** [comment]
LGTM!
