### ISSUE TITLE
Document application objects and terms

### ISSUE THREAD

**Issue by Pointer2VoidStar** [dribdat/dribdat#235]
I have recently come across dribdat and although it seems very capable, after playing around with it, a few things are quite jarring.

First of all, it is not at all clear, what the relationship is between the following entities:

Event
Project
Team
Challenge
Idea[?]

For example [here](https://github.com/hackathons-ftw/dribdat/blob/main/USAGE.md#what-does-it-look-like), there is the sentence: "Logged-in users can submit challenges, ideas and projects ..." - yet no attempt to explain the relationship between these entities - and I am yet to come across an option that allows me to submit an idea (perhaps - it is called something else - yet again?).

Is there an object model diagram somewhere that explains the relationships - or can someone simply point out the relationship?

Obviously, the Event is the parent model, to which the other entities belong. However, the relationship between a Project/Team/Challenge is anything but clear.

Perhaps, if clear definitions were given, it would be easier to infer the relationships.

So my questions are:

1. What are the relationships between Events, Project, Teams, Challenges and Ideas? 
2. What is(are) the difference(s) between a Project and a Challenge?

**Comment by loleg** [comment]
Thanks very much for your encouragement & critical feedback. It is helpful to get a second opinion on terminology, both to clarify and help revise it for the next iterations. I'll try to briefly answer your two questions here, though this definitely belongs in documentation (hence my renaming of the issue). See also #133

(1) What are the relationships between Events, Project, Teams, Challenges and Ideas?

One starts a hackathon **Event**, to which Challenges (= Ideas) are added. These can take the form of **Projects** (at progress level 0), or **Categories**. A team is simply any number of **Users** who have joined a **Project**. I've put in bold the words which are actual dribdat classes. There is currently no diagram, so I quickly started one we can iterate on (just click to edit). All the main models are represented here:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBFdmVudCAtLS0gUHJvamVjdFxuICAgIFByb2plY3QgLS0tIFVzZXJcbiAgICBQcm9qZWN0IC0tLSBDYXRlZ29yeVxuICAgIFByb2plY3QgLS0tIFByb2dyZXNzXG4gICAgQWN0aXZpdGllcyAtLS0gVXNlciAmIFByb2plY3QgJiBSZXNvdXJjZVxuICAgIFVzZXIgLS0tIFJvbGUiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBFdmVudCAtLS0gUHJvamVjdFxuICAgIFByb2plY3QgLS0tIFVzZXJcbiAgICBQcm9qZWN0IC0tLSBDYXRlZ29yeVxuICAgIFByb2plY3QgLS0tIFByb2dyZXNzXG4gICAgQWN0aXZpdGllcyAtLS0gVXNlciAmIFByb2plY3QgJiBSZXNvdXJjZVxuICAgIFVzZXIgLS0tIFJvbGUiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

(2) What is(are) the difference(s) between a Project and a Challenge?

- A Challenge is a problem statement, often with some elaboration of some ideas of how to address it - at a hackathon, this typically involves links to technical tools, datasets, or information resources.
- A Project contains evidence of work that has been done - typically but not always in response to a specific Challenge, as often as possible with links to documentation, source code, presentation, or any other relevant artifacts.

Does this help? Do you have examples of excellent descriptions of this kind from other software projects?

**Comment by loleg** [comment]
This has been now added to the documentation. If there are no more questions, I think we can close the issue.

**Comment by Pointer2VoidStar** [comment]
Thanks for the detailed response and the included object diagram. That helps a lot!
