### ISSUE TITLE
Store events in repositories

### ISSUE THREAD

**Issue by tamberg** [dribdat/dribdat#256]
This might be a bit of a long shot idea. In addition to aggregating projects hosted on GitHub/GitLab, consider using repos to store the hackdays themselves. Maybe even host Dribdat right on GitHub Pages (or something similar for GitLab)? This could simplify the setup, reduce hosting cost, and help with archiving.

**Comment by loleg** [comment]
Yes! See also #112 and #214 - what we need is, basically, is a complete export of event metadata in a form that could be well stored in a repository. Probably easiest initially as a ZIP file download from the user interface.

**Comment by loleg** [comment]
Initial branch to test this: https://github.com/loleg/dribdat/tree/datapackage

**Comment by loleg** [comment]
Working build deployed: see [#259](https://github.com/dribdat/dribdat/pull/259#issuecomment-876260861) for the ability to download a ZIP file containing a full data package, that is a step towards Git-hosted dribdat events. @tamberg

**Comment by loleg** [comment]
What kind of features - or at least, what kind of information (countdown timer? terms? resources? ...) - should we also be bundling into a static site? I think the basic requirement of "storing events" has been met, but of course we can build a lot from here. I would say that further issues and ideas would be more appropriate at [dribdat/backboard](https://github.com/dribdat/backboard/issues), and close this.
