### ISSUE TITLE
Checklists for hackday organizers

### ISSUE THREAD

**Issue by tamberg** [dribdat/dribdat#257]
Providing simple checklists for hackday organizers might help them organise hackdays. If hackdays are hosted on GitHub/GitLab (as proposed in #256), providing GitHub/GitLab project boards with pre-filled tasks might make getting started even easier.

**Comment by loleg** [comment]
![Bildschirmfoto von 2021-07-04 15-33-02](https://user-images.githubusercontent.com/31819/124387973-db011b80-dce0-11eb-9656-2554343cc2cf.png)

It this what you were thinking of? Deployed on https://meta.dribdat.cc/ - make an account, ping me to promote you to admin, start an event to see this screen.

**Comment by loleg** [comment]
I've started a [meta-project](https://github.com/orgs/dribdat/projects/2) as you suggested. There should be a way to make it into a template. Anyway, you are added as admin - feel free to make changes.

**Comment by loleg** [comment]
We can recommend the template meta-project by linking from the instructions. We could of course put more effort (ask someone to review?..) the content. But I think the basic need has been met. @tamberg agree?

**Comment by loleg** [comment]
Let's say we agree for now. Please re-open if you'd like to see more happening here.
