### ISSUE TITLE
Bug in Personal log time stamps

### ISSUE THREAD

**Issue by Martin1877** [dribdat/dribdat#263]
There seems to be a bug in the personal log timestamps. The dates there are for example not one hour ago but then 23 hours ago.

**Comment by loleg** [comment]
The issue is that the timestamps are saved in UTC time, and the server configuration is ignored. It probably makes sense to save them directly in the local time zone going forward.

**Comment by loleg** [comment]
Fixed in the new release, which has been deployed and tested. The "[time since](https://meta.dribdat.cc/dribs)" is shown correctly. Note that the mouseover title still shows the UTC date, though I'm not sure why.
