### ISSUE TITLE
Support popular authentication (IAM) providers 

### ISSUE THREAD

**Issue by loleg** [dribdat/dribdat#280]
Currently dribdat supports a couple of well-known authentication providers (like GitHub), which allow managing user accounts externally. Someone who installs the app into their infrastructure might want to use another one. For example, we are interested in connecting to:

- [Zitadel](https://hacknight.dinacon.ch/project/51) (great team! see [docs here](https://zitadel.com/docs/guides/integrate/login-users) and [Flask demo](https://github.com/zitadel/example-api-python3-flask/))
- [Supertokens](https://supertokens.io/) (cool tool but does [not yet support](https://supertokens.com/docs/phonepassword/architecture#what-about-oauth-20-flows) OAuth 2.0)
- [Auth0](https://auth0.com/) (market leader)
- [WebAuthn](https://webauthn.guide/) 
- [Authentik](https://goauthentik.io/).

We should provide instructions in our documentation for [generic OAuth](https://docs.dribdat.cc/deploy.html#authentication) providers. The library we use for authentication supports a number of other popular [authenticators](https://flask-dance.readthedocs.io/en/latest/providers.html). We should at least enable the [custom provider](https://flask-dance.readthedocs.io/en/latest/providers.html#custom) option, and look into the [multi-provider](https://github.com/singingwolfboy/flask-dance-multi-provider) support.

Criteria for including providers could include:

- Ease of use (for participant and organizer)
- Service quality
- Spam-protection
- Privacy-friendly
- Swiss or EU hosted
- Sponsorships

See also #261

**Comment by fforootd** [comment]
Hi there one of the founder of ZITADEL here 👋 

Happy to assist you with a ZITADEL integration or if you have general questions to OpenID Connect, OAuth and also SAML but thats not my favourite 😁

**Comment by loleg** [comment]
A couple more ideas: [WebAuthn](https://webauthn.guide/) and [Authentik](https://goauthentik.io/)

**Comment by loleg** [comment]
@fforootd Zitadel support has been implemented and tested a while ago. Our [sandbox](https://meta.dribdat.cc) currently has it enabled. I've added a link to our project in [ADOPTERS.md](https://github.com/zitadel/zitadel/pull/9021)
