### ISSUE TITLE
Challenge and project/result presentation on top of project page

### ISSUE THREAD

**Issue by florihas** [dribdat/dribdat#359]
As an interested person who has(n't) been at the hackathon and hasn't worked on _a_ specific project, I want to browse through the challenges/projects of a particular event and quickly get an idea of what the challenges i.e. problems were that the teams were trying to solve, which data (and tools) they have worked with and what result they came up with, to get to know the awesome projects and great work the teams are doing.

Thus, the project/result presentation *followed by the challenge/start presentation/description* should be prominent e.g. on top of every project page.

**Comment by loleg** [comment]
I understand this need, and agree that it's a critical aspect of the design. Currently the README (usually, the result of the project work) is underneath the PITCH (usually, the challenge). Let's reverse the order, and make it more clear what should be used when.
