### ISSUE TITLE
accessing version history of projects through log posts/files

### ISSUE THREAD

**Issue by florihas** [dribdat/dribdat#360]
As an interested person who has(n't) been at the hackathon and hasn't worked on _a_ specific project, I want to explore a project/challenge in-depth and see how the team went at it and progressed, to get to know the awesome projects and great work the teams are doing and learn from them.

So it would be great if people can access the version history of a project (description/text fields, demo links, other links etc.) e.g. via clicking on a button/text on the log posts/files

**Comment by loleg** [comment]
Extension of #357 and part of #358
