### ISSUE TITLE
Markdown: missing strikethrough text support

### ISSUE THREAD

**Issue by gonzalocasas** [dribdat/dribdat#95]
The markdown parser in dribdat does not seem to support strikethrough text the same way github-flavored markdown does:

**Dribdat**
![image](https://cloud.githubusercontent.com/assets/933277/23338748/5b8d83a0-fc13-11e6-89a6-6aa87990d1d3.png)

**Github**
![image](https://cloud.githubusercontent.com/assets/933277/23338755/a3d205b4-fc13-11e6-9a75-45195fdff9e6.png)

**Comment by loleg** [comment]
Thanks. This is a [configuration setting](https://flask-misaka.readthedocs.io/en/latest/) in the Misaka parser for Markdown. Enabled and deployed.
